name: nlp-tutorials
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - spacy-model-en_core_web_sm
  - spacy-model-en_core_web_md
  - spacy-model-en_core_web_lg
  - pip:
    - -r requirements.txt 